- src/PrivateRoute.tsx
- src/pages/Dashboard/Dashboard.tsx
- src/pages/LogIn/components/LoginForm.tsx
- src/routes.tsx
Improve security and user experience by directly re-routing users back to the log-in page, if detected to be not logged in previously. Avoids bugs that arise due to user accessing the Dashboard (or other private pages) without proper security and removes error that arose from ChRIS when this occurred
Route guard checks for user being logged in and directs user accordingly, making sensitive pages private
> Added Route Guard to COVID-Net UI for Dashboard, Create Analysis, and View Image pages

- src/components/CreateAnalysis/CreateAnalysisWrapper.tsx
- src/pages/Dashboard/Dashboard.tsx
When a user selects scans and starts the analysis and then returns back to the same patient to start another analysis but for other scans, the previous scans are still selected.
Dispatch `Clear_selected_studies_UID` in `submitAnalysis()` as opposed to after analyses are completed.
Steps to Reproduce
1. Log into COVIDNet Portal
2. Enter a Patient MRN and press Continue
3. Select an XRay or CT scan
4. Click Analyze to start the analysis
5. A user gets redirected to dashboard
6. Navigate to a patient again in order to start another analysis
Actual Behaviour
- DICOMs remain selected on Create Analysis page until the previous analyses are completed.
Expected Behaviour
- DICOMs should immediately be de-selected upon analyzing.
> [CNXC-181] Clear DICOM selections on analysis

- src/RouterWrapper.tsx
- src/api/chrisapiclient.ts
- src/containers/Layout/Header.tsx
- src/containers/Layout/PageWrapper.tsx
- src/context/reducers/userReducer.tsx
- src/main.tsx
- src/pages/LogIn/components/LoginForm.tsx
- src/services/login.tsx
- src/types/chrisapi/index.d.ts
COVID-Net UI should support multiple user accounts (leveraging the ChRIS backend). Currently, the UI has a single user hardcoded into the implementation (chris1234); this should be updated to dynamically use the current user logged into the UI.
- Remove all hard-coded user data.
- Remove password property from user store
- Ensure that `ChrisAPIClient tokenIsUnauthorized` is set to `true` when user logs out to prevent auth token from being carried over across multiple sessions.
- Move up code for checking if user is already authenticated to new RouterWrapper component
- Automatically redirect from Login to Dashboard if user already authenticated
> [CNXC-193] Multi-user functionality

- src/components/pastAnalysis/seriesTable.tsx
There is some inconsistency in the formatting of the headers of the SeriesTable. The first 2 columns have headers in black, while the rest are grey.
The SCSS class for styling the headers as grey were applied to the first 2 header elements.
> [CNXC-244] Fix styling of SeriesTable header

- src/pages/LogIn/components/LoginForm.tsx
- Currently, when the user provides invalid user credentials on the Login page and tries to log in, there are no visual indicators to inform the user.
- The "Remember me" option is present on the login component but is not being used.
- Utilized the `helperText` and `isValid` props provided by the PatternFly LoginForm component to display login errors to the user.
- Removed the "Remember me" option
> [CNXC-230] Add UI for invalid login credentials + Remove "Remember me" option

- src/components/CreateAnalysis/CreateAnalysisWrapper.tsx
- src/pages/CreateAnalysisPage/CreateAnalysisPage.tsx
- src/pages/Dashboard/Dashboard.tsx
Currently, after starting an analysis, COVID-Net re-runs the same analysis if the user goes to `Create Analysis` and routes back to `Dashboard` (before the previous analysis has finished)
Refactored code to create the analysis in CreateAnalysis, instead of Dashboard. Doing this, this resolves the issue of having mixed concerns and a bug of triggering current analyses to re-run when routing back to Dashboard repeatedly. Code now separates concerns and resolves the bug
> [CNXC-247] Re-running Current Analyses when Routing Back to Dashboard

- src/assets/scss/components/DicomImageViewer.scss
- src/components/dicmViewer/dicomViewerBottomBox.tsx
The bottom box on the Dicom Viewer page does not scale well. Its height should scale along with its contents.
- `em` units were used instead of `vh` to allow for responsiveness when zooming in and out of the page
- `flex` property was used for responsiveness on narrower screens
> [CNXC-202] Fix responsiveness issues with Dicom Viewer

- src/components/CreateAnalysis/CreateAnalysisDetail.tsx
- src/components/PatientLookup.tsx
Currently, the patient MRN box is empty after performing a search, and also after routing back to the Create Analysis page.
Added createAnalysis store into CreateAnalysisDetail useEffect's dependency to now update and display the current patient MRN correctly, and also keep/store the value when re-routing back to the Create Analysis page during the same session. The value now stays in sync with Create Analysis page patient content.
> [CNXC-249] Patient MRN not displaying after search/re-routing

- src/context/reducers/createAnalysisReducer.tsx
DICOM files remain selected after re-searching for the same patient.
1. Search for a patient "A"
2. Select a DICOM file
3. Search for another patient "B"
4. Search for patient "A". The DICOM file that was selected will remain selected
The Create Analysis Reducer was modified to clear the `selectedStudyUIDs` and `currSelectedStudyUID` when the `patientID` is updated.
> [CNXC-248] Clear selected UIDs on new patient search

- src/assets/scss/components/PatientLookup.scss
- src/components/PatientLookup.tsx
The Privacy Level select field used for anonymization of data needs to be removed from the dashboard page.
Originally, the purpose of that setting was to anonymize personal data during public demos. 
Removed the Privacy Level drop-down from the PatientLookup component, (along with any of its dependent code), then adjusted styling of the patient look-up bar
> [CNXC-292] Remove Privacy Level field Drop-down

- src/services/chris_integration.tsx
Remove ` WAITING_FOR_PREVIOUS = "waitingForPrevious",` from `PluginPollStatus` enum.
> [CNXC 182] Update plugin status options

- .github/workflows/github-ci.yml
**CI to Docker Hub**
Added Github workflow for building and pushing a Docker image to Docker Hub whenever a new `release` is published.
> [CNXC-282] CI to Docker Hub

- src/assets/scss/layout/_layout.scss
- src/assets/scss/layout/layout.scss
- src/components/CreateAnalysis/CreateAnalysis.tsx
- src/containers/Layout/Header.tsx
The header title appears as a click-able feature for routing, but does not re-route the user back anywhere
Added routing feature into COVID-Net title in header, changed <span> to <button> tag, and calling on the history hook to link back to the Dashboard
> [CNXC-302] Add routing feature into COVID-Net Title in Header

- src/assets/scss/main.scss
- src/containers/Layout/Header.tsx
The header logo contents, which contain an `<a>`, were being wrapped in an `<a>` by default. Anchors cannot be nested in an anchor.
Use the logoComponent prop to change the logo wrapper to be a `<div`.
> [CNXC-302] Fix header logo wrapper

- src/components/CreateAnalysis/CreateAnalysisDetail.tsx
- src/components/CreateAnalysis/CreateAnalysisWrapper.tsx
- src/components/CreateAnalysis/SelectedStudyDetail.tsx
- src/components/CreateAnalysis/SelectionStudy.tsx
- src/context/reducers/dicomImagesReducer.tsx
- src/services/CreateAnalysisService.tsx
- src/services/chris_integration.tsx
- src/services/pacs_integration.tsx
Currently, the date being displayed under each study is not the study date and the Series are labelled using their DICOM file names. The UI should be reading the StudyDate and SeriesDescription properties from the DICOM metadata and display these instead.
With the new updates made to CUBE, `getPACSFiles` now returns a DICOM metadata object that includes the StudyDate, so this is used to display the appropriate date under each study. The SeriesDescription is now being used instead of the fname to label each series.
> [CNXC-294] Use StudyDate and SeriesDescription on CreateAnalysisPage

- src/components/CreateAnalysis/ImageSelectionBox.tsx
- src/components/pastAnalysis/seriesTable.tsx
Showing image file names for studies in PastAnalyses isn't desirable behaviour. Instead, we want to have Series Descriptions for each image (shown below for example)
Replacing it in the same location
> [CNXC-343] Display Series Description in dropdown for each study in PastAnalyses 

- src/components/pastAnalysis/PastAnalysisTable.tsx
**Problem**
After conducting a meeting with FNNDSC and Red Hat, a new design of the rows of the table was proposed that would remove the blue/red/grey badges on the very right which indicated the number of images and errors.
**Solution**
3 steps were taken to make this change:
1. The original badges were removed.
2. A column for the # of images was added after the Study Date column.
3. A column for the status along with a corresponding icon was added at the beginning of the row.
> [CNXC-307] Re-design Past Analysis Table

- src/components/dicmViewer/dicomViewerBottomBox.tsx
The only ways to properly access the DICOM viewer page should be from ‘View Image’ from the Dashboard analyses rows, or from the notification panel.
Going there directly, or reloading the page once already there will result in a blank DICOM viewer page, and the app should re-direct the user to the Dashboard again. 
We get a blank DICOM viewer page only if the information isn't acquired through our desired means (by pressing View from one of the rows of the PastAnalysis table), so under these cases, we are good to redirect back to the Dashboard.
> [CNXC-347] Reroute if series information is unavailable

- src/components/PatientLookup.tsx
- src/pages/CreateAnalysisPage/CreateAnalysisPage.tsx
While wait times for fetching from a local Swift or PACS are negligible, in a production environment, there will be significant delay. So, while we are in the process of searching, we will visually indicate that fetching is occurring with a spinner.
> [CNXC-254] Implement loading UI for patient search

- src/services/chris_integration.tsx
PastAnalyses table was retrieving most recent plugin instance/resource's files instead of the specific model's files, so the right information was being failed to be displayed. This was fixed by looking specifically for the model's plugin name in the list of plugin instances and using that plugin instance.
> [CNXC-364] Fix post-pdf-generation PastAnalyses table row showing analysis failed

- src/services/chris_integration.tsx
One of the FNNDSC workflows requires the usage of png files, and they’d encounter issues accessing the png files because of the hardcoded assumptions that we use a jpg (from med2img). 
Before
After
ChrisUI
> [CNXC-376] Add PNG file support for chris files

- src/containers/Layout/Header.tsx
> [CNXC-365] Remove link from COVID-NET text in navbar

- src/components/pastAnalysis/PastAnalysisTable.tsx
I decided to make it so that showing that the task is finished would be based on whether at least one of the feeds (not necessarily all of them) in that row showed up as finished instead of using time stamps. Feeds are unique to their rows, so I thought this would be better desired behaviour, although the tradeoff is needing another more global (component level) variable tying into that function.
Old #75
> [CNXC-344] Highlighting Newly Finished Study Analyses Rows on the Past Analysis Table

- src/services/CreateAnalysisService.tsx
Problem:
When looking up MRN on create new analysis screen, the list of studies on the left is not always in date order.
Looks like studies are sorted lexicographically in descending order first, then by date
Suggestion:
Always list studies in reverse chronological order when displaying MRN results here: most recent study on top down to least recent studies.
> [CNXC-402] Add sorting by study date then study desc to study instance extraction

- src/components/CreateAnalysis/SelectedStudyDetail.tsx
- src/components/CreateAnalysis/SelectionStudy.tsx
Problem:
It was unclear for some testers that as they selected studies in the left panel of the create new analysis screen, that the right side was updating accordingly. Likely this is exacerbated due to repetitive, filler metadata on the test data. However, a stronger visual link between the left panel and right panel would definitely improve the usability of this screen.
Solution:
- Highlight study row (like it currently is when you select a series from that study) whenever you select that study instead of the status quo
- Add date at the top of series selection panel
> [CNXC-403] Selected study clarity

- src/components/pastAnalysis/PastAnalysisTable.tsx
- src/services/chris_integration.tsx
Problem:
The MRN search box for past analyses was pretty unforgiving and a number of copy/paste errors, extra spaces, added dashes, etc. caused a lot of confusion and delay in finding past analyses.
Solution:
We requested for partial feed name filter matching functionality from the ChRIS team and added it as a new parameter. We also added some additional error components to be more informative to users.
Note: partial feed name filter matching works after this [commit](https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/337/commits/466a2b654d177b341859eefc8fb8207e498e8058) in the ChRIS backend.
Message when there have been no analyses/predictions made.
Regular dashboard
Search for invalid prediction
Partial name matching and filtering
> [CNXC-405] improve MRN search in PastAnalyses table

- src/components/pastAnalysis/PastAnalysisTable.tsx
Problem:
The past analysis results only lists MRN and not patient name, making the location task a little more difficult as it involves scanning long MRN numbers rather than looking for a recognizable patient name.
Screenshot of change:
> [CNXC-406] Add patient name as column to PastAnalysisTable

- src/components/dicmViewer/dicomViewerHeader.tsx
Tooltips should reflect their visual icon (eg. grab icon has scroll/ zooming functionality, zoom icon has grab functionality)
> [CNXC-407] Fix tooltips information in dicom viewer header

- src/components/PatientLookup.tsx
- src/pages/CreateAnalysisPage/CreateAnalysisPage.tsx
Create analysis page retained current patientId and images even when switching to other pages and logging out. It was determined that this was generally undesirable behaviour, so we made it so that state is reset whenever the user leaves the page.
> [CNXC-409] Removal of image state retention for create analysis page 

- src/assets/scss/components/CreateAnalysisDetail.scss
Problem:
On lower-resolution screens, “create analysis” button in upper right corner of screen is not visible and can take a lot of scrolling to reach
Solution: 
Make Analyze button and its surrounding components in CreateAnalysis page fixed with respect to the page
> [CNXC-404] Make Analyze button fixed to page and add border

- README.md
- src/RouterWrapper.tsx
- src/components/CreateAnalysis/CreateAnalysisWrapper.tsx
- src/components/dicmViewer/dicomViewerHeader.tsx
- src/containers/Layout/PageNav.tsx
- src/pages/Dashboard/Dashboard.tsx
- src/routes.tsx
Similar to #96, but with terminology changes only within comments, documentation, and the UI itself. This also includes fixes from making ordering switches in the first place. Therefore, for the most part, it does not impact functionality of other components.
> [CNXC-401] page ordering fork without code-specific terminology change

- README.md
Don't want to finalize this just yet because it'd be preferable to avoid treating pl-grad-cam as a special case while it lacks a CI/CD pipeline that uploads it to docker hub through fnndsc.
> Update readme with grad cam instructions
